page1:
  items:
    w-yun-chui:
      data:
        animate: slideInLeft
        time: 500
    w-xing-shuang:
      data:
        animate: flash
        infinite: true
        duration: 4s
        time: 1000
    w-wang-yuan-jing:
      data:
        animate: tada
        time: 500
    w-yun-xing:
      data:
        animate: slideInRight
        time: 500
    w-qi-qiu:
      data:
        animate: slideInDown
        time: 1500
    w-text-yang-guang:
      data:
        animate: flash
        duration: 6s
        infinite: true
        time: 500
    shan-fang-lu:
      data:
        animate: fadeIn
        time: 500
    tan-suo-yu-zhou:
      data:
        animate: bounceInUp
        time: 1000
        duration: 1s
    chao-ji-jie-bao:
      data:
        animate: bounceInUp
        time: 1000
        duration: 1s
page2:
  xiaoRenTime: 2000
  items:
    w-fei-ji-right:
      data:
        animate: slideInLeft
        time: 300
    w-xing-xiao:
      data:
        animate: swing
        time: 300
        infinite : true
    w-fang-da-jing:
      data:
        animate: fadeIn
        time: 500
    w-dna-fenzi:
      data:
        animate: rotateIn
        time: 1000
    w-dian-nao:
      data:
        animate: fadeIn
        time: 1100

    data-board:
      data:
        animate: fadeIn
        time: 2000
    bi-fei-ren-1:
      data:
        animate: fadeInUp
        time: 1000
    line-mulit-s:
      data:
        animate: slideInUp
        time: 1100
        duration: 0.5s
    di-yi-zhang:
      data:
        animate: slideInUp
        time: 500
    awar-text:
      data:
        animate: slideInUp
        time: 500
    da-bao-guang:
      data:
        animate: slideInUp
        time: 500
    ren-qun-jing-zhui:
      data:
        animate: fadeIn
        time: 1000
page3:
  items:
    w-di-yi-icon-2:
      data:
        animate: fadeIn
        time: 300

    w-fei-ji-right:
      data:
        animate: fadeInLeft
        time: 500
    w-yun-xing:
      data:
        animate: fadeInRight
        time: 500
    w-deng-pao:
      data:
        animate: flash
        time: 500
        duration: 4s
        infinite : true
    w-huo-pao:
      data:
        animate: bounceInRight
        time: 500
    w-dian-shi:
      data:
        animate: slideInRight
        time: 500
    wu-da-mei-ti:
      data:
        animate: zoomIn
        time: 1000
    intro-card:
      data:
        animate: fadeIn
        time: 1800

    shou-ji-ke:
      data:
        animate: fadeIn
        time: 1600
    shou-ji-li:
      data:
        animate: fadeIn
        time: 1600
page4:
  items:
    w-yun-xing:
      data:
        animate: fadeInRight
        time: 500
    w-yan-hua:
      data:
        animate: slideInUp
        time: 500
    bg-mask:
      data:
        animate: fadeIn
        time: 100
        duration: 0.2s

    tan-suo-bao-guang:
      data:
        animate: fadeInUp
        time: 500
    xian-shang-bao-guang:
      data:
        animate: fadeInDown
        time: 800
    popu-borad:
      data:
        animate: bounceInDown
        time: 200
        duration: 600ms
    di-yi-icon:
      data:
        animate: fadeIn
        time: 600
    num-text-7:
      data:
        animate: bounceIn
        time: 1100
    yi-word:
      data:
        animate: lightSpeedIn
        time: 1200
        duration: 500ms

page5:
  scrollnums:
    num:
      type: blue
      time: 1800
      val: 1236
      duration: 1000
  items:
    w-di-yi-icon-2:
      data:
        animate: fadeIn
        time: 300
    w-da-mu-zhi:
      data:
        animate: pulse
        time: 1500
        infinite: true
    w-xiao-huo-pao:
      data:
        animate: fadeInLeft
        time: 300
    w-peng-you:
      data:
        animate: fadeInRight
        time: 300
    w-jiang-bei:
      data:
        animate: fadeInUp
        duration: .5s
        time: 1500
    w-huo-pao:
      data:
        animate: fadeIn
        time: 1600
    w-xing-shuang:
      data:
        animate: flash
        infinite: true
        time: 2400
        duration: 8s
    wan-word:
      data:
        animate: fadeIn
        time: 1800
    dou-hao1:
      data:
        animate: fadeIn
        time: 1800
    fu-hao-add:
      data:
        animate: fadeIn
        time: 1900
    tan-suo-bao-guang:
      data:
        animate: fadeInDown
        time: 100
    lei-ji-xin-zeng:
      data:
        animate: bounceInUp
        time: 1000
    mao-er-chart-board:
      data:
        animate: fadeInUp
        time: 1600
page6:
  # scrollnums:
  #   num:
  #     type: blue
  #     time: 3200
  #     val: 20
  #     duration: 1500
  items:
    w-fang-da-jing:
      data:
        animate: pulse
        infinite: true
        duration: 2s
        time: 1200
    w-dna-fenzi:
      data:
        animate: rotateIn
        time: 500
    w-fei-ji-right:
      data:
        animate: slideInLeft
        time: 500

    yun-xing-da:
      data:
        animate: slideInRight
        time: 500
    w-jiang-bei-ren:
      data:
        animate: zooomIn
        time: 6500

    w-up-down-arrow:
      data:
        animate: fadeIn
        time: 2200
    tan-suo-hu-dong:
      data:
        animate: fadeInUp
        time: 1000
    di-er-zhang:
      data:
        animate: fadeIn
        time: 1200
    interest:
      data:
        animate: fadeInUp
        time: 1000
    num-text-30:
      data:
        animate: fadeInUp
        time: 2000
    yi-jian-ling-xiu:
      data:
        animate: fadeInUp
        time: 2400

    fu-hao-add:
      data:
        animate: tada
        infinite: true
        duration: 4s
        time: 2600

    board-wan-shua:
      data:
        animate: fadeIn
        time: 2200
    san-zhang-tu:
      data:
        animate: fadeIn
        time: 2500
    san-ya-huo-dong-1:
      data:
        animate: slideInLeft
        time: 1900
    li-na-tu:
      data:
        animate: fadeIn
        time: 1800
    board-ya-zi:
      data:
        animate: fadeIn
        time: 1500

page7:
  scrollnums:
    num:
      type: blue
      time: 2000
      val: 6131
      duration: 1500
  items:
    w-di-er-icon-2:
      data:
        animate: fadeIn
        time: 300
    w-fei-ji-right:
      data:
        animate: fadeInLeft
        time: 2000
        infinite: true
        duration: 10s
        delay: 1000
        direction: alternate
    w-yun-xing:
      data:
        animate: fadeInRight
        time: 500
    w-xiao-nan-hai:
      data:
        animate: fadeInUp
        time: 1000
    w-dou-hao:
      data:
        animate: fadeIn
        time: 2000
    wan-jia-word:
      data:
        animate: fadeIn
        time: 2000
    w-xiao-nv-hai:
      data:
        animate: pulse
        time: 3500
        infinite: true
        duration: 5s
        direction: alternate
    w-xian-kuang:
      data:
        animate: zoomIn
        time: 2800
    w-huo-pao:
      data:
        animate: fadeIn
        time: 2200
    w-mao-er-board:
      data:
        animate: bounceInDown
        time: 500
    dot-word:
      data:
        animate: fadeIn
        time: 2600
    tan-suo-dong:
      data:
        animate: fadeInDown
        time: 200
    wan-jia-bg:
      data:
        animate: fadeIn
        time: 2000
    wu-zhang-tu:
      data:
        animate: zoomIn
        time: 2800
    zhi-bo-guan-kan:
      data:
        animate: fadeIn
        time: 1300
page8:
  scrollnums:
    num:
      type: blue
      time: 2000
      val: 106
      duration: 1200
  items:
    bg-mask:
      data:
        animate: fadeIn
        time: 0
    w-xiao-xiong:
      data:
        animate: swing
        time: 1500
    tan-suo-dong:
      data:
        animate: fadeInDown
        time: 1400

    di-er-icon:
       data:
        animate: fadeIn
        time: 900
    w-bi-xin:
      data:
        animate: flash
        infinite: true
        time: 2500
        duration: 6s
    board-8:
      data:
        animate: bounceInDown
        time: 200
        duration: 600
    p-55:
      data:
        animate: slideInUp
        time: 2500
    dot-word:
      data:
        animate: fadeIn
        time: 2200
    wan-word:
      data:
        animate: slideInRight
        duration: .5s
        time: 2200
    fen-si-zeng-zhang:
      data:
        animate: fadeInUp
        time: 1400
    w-wang-yuan-jing:
      data:
        animate: swing
        time: 2500
page9:
  # scrollnums:
  #   num:
  #     type: blue
  #     time: 3800
  #     val: 200
  #     duration: 1200
  items:
    w-di-er-icon-2:
      data:
        animate: fadeIn
        time: 200
    w-fei-ji-right:
      data:
        animate: fadeInLeft
        time: 300
    w-yun-xing:
       data:
        animate: slideInRight
        time: 300
    w-re-qi-qiu:
      data:
        animate: fadeOutUp
        time: 500
        infinite: true
        duration: 10s
        delay: 1000
        direction: alternate
    w-wang-yuan-jing:
      data:
        animate: zoomIn
        time: 500
    w-huo-pao:
      data:
        animate: fadeIn
        time: 500
    w-xiao-nv-hai:
      data:
        animate: flipInY
        time: 500
    w-x-zhou:
      data:
        animate: fadeIn
        time: 800
    w-up-right-arrow:
      data:
        time: 2400
    w-left-bar:
      data:
        time: 1400
    w-right-bar:
      data:
        time: 2800
    num-text-130:
      data:
        animate: tada
        time: 3800
    tian-word:
      data:
        animate: fadeIn
        time: 4200
    huo-dong-zeng-zhang:
      data:
        animate: flipInY
        time: 1000
    guo-qu-zeng-zhang:
      data:
        animate: flipInY
        time: 2000
    xiang-dang-yu-past:
      data:
        animate: fadeInLeft
        time: 3000
    ji-lei-fen-liang:
      data:
        animate: fadeInRight
        time: 3000

page10:
  items:
    w-fei-ji-right:
      data:
        animate: slideInLeft
        time: 200
    w-xing-xiao:
      data:
        data:
        animate: rotate
        infinite: true
        duration: 20s
        time: 300
    w-fang-da-jing:
      data:
        animate: rotateInUpRight
        time: 1200
    w-da-mu-zhi:
       data:
        animate: tada
        infinite: true
        duration: 4s
        time: 2000
    w-yun-que:
      data:
        animate: fadeIn
        time: 2000
    w-bi-fei-ren:
       data:
        animate: rotateInDownLeft
        time: 500
    w-tian-wen-jing:
       data:
        animate: rotateInDownRight
        time: 500

    di-san-zhang:
      data:
        animate: fadeIn
        time: 600
    pucharse:
      data:
        animate: fadeInUp
        time: 800
    tan-suo-gao-xiao:
      data:
        animate: fadeInUp
        time: 800
    p-2:
      data:
        animate: zoomIn
        time: 1500
    quan-nian-top2:
      data:
        animate: zoomIn
        time: 1500

page11:
  scrollnums:
    num:
      type: blue
      time: 1400
      val: 30
      duration: 1200
  items:
    w-di-san-icon-2:
      data:
        animate: fadeIn
        time: 200

    w-fei-ji-right:
      data:
        animate: fadeInLeft
        time: 2000
        infinite: true
        duration: 10s
        delay: 1000
        direction: alternate
    w-yun-xing:
      data:
        animate: slideInRight
        time: 200
    w-jiang-bei-ren:
      data:
        animate: fadeIn
        time: 2000
    w-x-zhou-1:
      data:
        animate: fadeIn
        time: 1000
    w-up-right-arrow-1:
      data:
        time: 2400
    w-left-bar-1:
      data:
        time: 1800
    w-right-bar-1:
      data:
        time: 2800
    bei-word:
      data:
        animate: fadeInUp
        time: 1800
    w-fen-zi:
      data:
        animate: tada
        infinite: true
        duration: 4s
        time: 500
    gao-xiao-liang:
      data:
        animate: fadeInUp
        time: 500
    shan-fang-lu:
      data:
        animate: fadeInUp
        time: 300
    xiang-dang-yu:
      data:
          animate: slideInLeft
          time: 800
    jin-ci-yu:
      data:
          animate: slideInRight
          time: 800
    text-ri-chang:
      data:
        animate: flipInY
        time: 1000
    chao-ji-xiao-liang:
       data:
        animate: flipInY
        time: 1800

page12:
  items:
    w-di-san-icon-2:
      data:
        animate: fadeIn
        time: 200
    w-fei-ji-right:
      data:
        animate: slideInLeft
        time: 500
    w-li-wu:
      data:
        animate: slideInRight
        time: 500
    w-dna-xuan:
      data:
        animate: rotateIn
        time: 500
    w-huo-pao:
      data:
        animate: zoomIn
        time: 2800
    w-xiao-nan-hai:
      data:
        animate: fadeInUp
        time: 3200

    gao-xiao-liang:
      data:
        animate: fadeInUp
        time: 500
    xiao-lan-he:
      data:
        animate: zoomIn
        time: 1000
    eight-hour:
      data:
        animate: fadeIn
        time: 1400
    num-text-1:
      data:
        animate: zoomIn
        time: 1400
    nai-fen-li-wu:
       data:
        animate: bounceInUp
        time: 1800

page13:
  items:
    w-fei-ji-right:
      data:
        animate: slideInLeft
        time: 500
    w-xing-xiao:
      data:
        animate: rotate
        infinite: true
        duration: 20s
        time: 800
    w-fang-da-jing:
      data:
        animate: tada
        infinite: true
        duration: 10s
        time: 5000
    w-left-arrow:
      data:
        animate: slideInRight
        time: 1800
    w-right-arrow:
      data:
        animate: slideInLeft
        time: 1800

    di-wu-zhang:
      data:
        animate: fadeIn
        time: 500
    loyalty:
      data:
        animate: fadeInUp
        time: 800
    tan-kou-bei:
       data:
        animate: fadeInUp
        time: 800
    san-ya-culb:
      data:
        animate: zoomIn
        time: 1000
    kuang-san-ya:
      data:
        animate: rotateInDownRight
        time: 1200
    # san-ya:
    #   classes: hide rotateIn
    er-tong:
      data:
        animate: rotateIn
        time: 1800
    di-ifer:
       data:
        animate: fadeIn
        time: 800

page14:
  scrollnums:
    num:
      type: blue
      time: 2000
      val: 332
      duration: 1200
  items:
    w-di-si-icon-2:
      data:
        animate: fadeIn
        time: 200
    w-yun-xing:
      data:
        animate: bounceInDown
        time: 500
    w-jiang-bei:
      data:
        animate: swing
        time: 2000
    w-yan-hua:
      data:
        animate: zoomIn
        time: 3000
    w-yun-chui:
      data:
        animate: rotateInDownLeft
        time: 2200
        duration: 2s
    w-shu-ben:
      data:
        animate: rotateInUpLeft
        time: 2200
        duration: 2s
    w-nai-fen:
      data:
        animate: rotateInUpRight
        time: 2200
        duration: 2s
    w-xiao-huo-che:
      data:
        animate: slideInUp
        time: 500
    w-xiao-fei-ji:
      data:
        animate: slideInDown
        time: 500
    w-wan-shua:
      data:
        animate: slideInUp
        time: 500
    w-xiao-nan-hai:
      data:
        animate: slideInUp
        time: 500
    w-xiao-huo-pao:
      data:
        animate: slideInUp
        time: 500

    # tan-suo-kou-bei:
    bai-ban-p-200:
      data:
        animate: rotateIn
        time: 500
    you-zhi-kou-bei:
      data:
        animate: fadeInDown
        time: 1500
    yu-du-hu-dong:
      data:
        animate: fadeInDown
        time: 1600
    # w-200:
    #   data:
    #     animate: rotateIn
    #     time: 4000
    w-word:
      data:
        animate: fadeIn
        time: 2200
    nan-nv-group:
      data:
        animate: zoomIn
        time: 2600
    hu-dong-liang:
      data:
        animate: rotateIn
        time: 3000

page15:
  scrollnums:
    num:
      type: blue
      time: 1800
      val: 760
      duration: 1200
  items:
    w-fei-ji-right:
      data:
        animate: slideInLeft
        time: 200
    w-xing-xiao:
      data:
        animate: slideInDown
        time: 500
    w-fang-da-jing:
      data:
        animate: rotateIn
        time: 500
    w-huo-pao:
      data:
        animate: zoomIn
        time: 3000
    w-lun-xin-lin-shou:
      data:
        animate: rotateIn
        duration: 30s
        time: 1500
    w-lun-tian-mao:
      data:
        animate: rotateIn
        duration: 30s
        time: 2000
    bai-fen-hao:
      data:
        animate: fadeIn
        time: 1800
    di-wu-zhang:
      data:
        animate: fadeIn
        time: 500
    summary:
      data:
        animate: fadeInUp
        time: 1000
    tong-bi-zeng-zhang:
      data:
        animate: fadeInUp
        time: 1000
    # p-89:
    #   data:
    #     animate: flipInY
    #     time: 2400
    sha-bao:
      data:
        animate: slideInUp
        time: 500

page16:
  # scrollnums:
    # xinke:
    #   type: blue
    #   time: 1800
    #   val: 89
    #   duration: 1200
    # zhengti:
    #   type: blue
    #   time: 1800
    #   val: 89
    #   duration: 1200
    # xiaoliang:
    #   type: blue
    #   time: 1800
    #   val: 89
    #   duration: 1200
  items:
    w-di-wu-icon-2:
      data:
        animate: fadeIn
        time: 300
    w-xue-xi:
      data:
        animate: slideInUp
        time: 500
    w-xiao-yun:
    tm-chao-icon:
      data:
        animate: fadeIn
        time: 1200
    w-xiao-fei-ji:
      data:
        animate: bounceInLeft
        time: 6500
    w-fen-zi:
      data:
        animate: tada
        infinite: true
        duration: 4s
        time: 4200
    tian-mao-chao-shi:
      data:
        animate: zoomIn
        time: 500
    circle-tu:
      data:
        animate: bounceIn
        time: 1200
    bai-fen-hao:
      data:
        animate: fadeIn
        time: 1800
    text-55-p:
      data:
        animate: flash
        time: 1200
    text-200-p:
      data:
        animate: flash
        time: 2000
    text-255-p:
      data:
        animate: flash
        time: 3400
    mao-chao-zeng-zhang:
      data:
        animate: flash
        time: 5200
    xin-ke-zeng-zhang:
      data:
        animate: flash
        time: 1800

    text-p-wenzi:
      data:
        animate: fadeInDown
        time: 4000
    shu-ju-fen-xi:
      data:
        animate: slideInDown
        time: 4500

page17:
  items:
    w-di-wu-icon-2:
      data:
        animate: fadeIn
        time: 300
    w-re-qi-qiu:
      data:
        animate: fadeInUp
        time: 2800
    w-yun-yang:
      data:
        animate: fadeIn
        time: 1000
    w-fei-ji-right:
       data:
        animate: fadeInLeft
        time: 500

    w-huo-pao:
      data:
        animate: fadeIn
        time: 800

    cheng-11:
      data:
        animate: fadeInDown
        time: 500
    da-run-fa:
      data:
        animate: zoomIn
        time: 2800
    xiao-yu-zhou-ts:
      data:
        animate: fadeInDown
        time: 2400
    china-ditu:
      data:
        animate: fadeIn
        time: 1400
    loc-icon:
      data:
        animate: fadeInDown
        time: 1800
page18:
  fzTime: 1000
  items:
    wei-lai-text:
      data:
        animate: pulse
        inifnite: true
        duration: 4s
        time: 2400
